@hostname = http://localhost:3001

GET {{hostname}}/api/notes

###
GET {{hostname}}/api/notes/62ec0723793ef51392dafda2


###
POST {{hostname}}/api/notes
Content-Type: application/json

{
    "content":"Hello11231",
    "important": false,
    "userId":"62f1f73bba11b41a70a562b9"
}

###
PUT {{hostname}}/api/notes/62ec0723793ef51392dafda2
Content-Type: application/json

{
    "content":"lol",
    "important": false
}

###
DELETE {{hostname}}/api/notes/62ec0723793ef51392dafda2